### ISSUE TITLE
Cannot initiate cluster

### ISSUE THREAD

**Issue by vp223** [Wittline/pyspark-on-aws-emr#1] opened 2021-07-12 18:54 UTC
**Describe the bug**
I put in my AWS credentials, then ran the command to create a cluster, but nothing happened. Returned nothing (no error and no output).

**To Reproduce**
1. aws.cmd configure
2. python emr_process.py -a create_cluster -c wittline

**Desktop (please complete the following information):**
 - Windows 10
 - Git Bash
 - AWS CLI 2

**Comment by Wittline** [comment] 2021-07-12 18:58
Hi @vp223,

I am covering your request, let me try to reproduce the error, I will back with you.

**Comment by vp223** [comment] 2021-07-12 18:58
Thank you!

**Comment by Wittline** [comment] 2021-07-19 03:30
Hi @vp223 I already tried and everything is working fine, 
Could you please make sure you are in the correct location of the folder?

ramse@DESKTOP-K6K6E5A MINGW64 **/c/pyspark-on-aws-emr/code** python emr_process.py -a create_cluster -c wittline

**Comment by vp223** [comment] 2021-07-21 19:34
I removed the "CreateBucketConfiguration" argument from the "create_cluster" function in s3.py and it worked for me. I will have to see why this location constraint always impedes creation of a bucket for me, not in this tutorial, but all tutorials.

**Comment by vp223** [comment] 2021-07-21 19:40
I just read that the default location is us-east-1, so listing this argument will obstruct progress for anyone whose location is such. I should have properly searched comments about the issue before raising it. I apologise. Won't happen again.

**Comment by Wittline** [comment] 2021-07-21 20:16
**Pending**:

Try updating your configuration file **cluster-ec2-spot-fleet.json** with your region zones and subnets. remember always delete your resources created

**Comment by Wittline** [comment] 2021-07-22 21:27
I will close this issue, the problem was related to the misunderstanding of the steps

**Closed as completed** 2021-07-22 21:27 UTC
